---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangbiliu.
--- DateTime: 2025/4/27 17:24
---

--1.参数列表：
--1.1 优惠券id
local voucherId = ARGV[1]
--1.2 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]

--1.3 当前时间(毫秒时间戳)
local currentTime = tonumber(ARGV[4])

--2.数据key
--2.1 开始时间key
local beginTimeKey = 'seckill:begin:' ..voucherId
--2.2 结束时间key
local endTimeKey = 'seckill:end:' ..voucherId
--2.3 库存key
local stockKey = 'seckill:stock:' ..voucherId
--2.4 订单key
local orderKey = "seckill:order:" ..voucherId

--3.脚本业务
--3.1 判断秒杀时间是否开始
local beginTimeStr = redis.call('get', beginTimeKey)
if (beginTimeStr) then
    local beginTime = tonumber(beginTimeStr)
    if (beginTime and currentTime < beginTime) then
        --秒杀尚未开始，返回3
        return 3
    end
end

--3.2 判断秒杀时间是否结束
local endTimeStr = redis.call('get', endTimeKey)
if (endTimeStr) then
    local endTime = tonumber(endTimeStr)
    if (endTime and currentTime > endTime) then
        --秒杀已经结束，返回4
        return 4
    end
end

--3.3 判断库存是否充足
local stockStr = redis.call('get', stockKey)
local stock = 0
if (stockStr) then
    stock = tonumber(stockStr)
end
if (stock <= 0) then
    --库存不足，返回1
    return 1
end

--3.4 判断用户是否下单  SISMEMBER orderKey userId
if (redis.call("sismember", orderKey, userId) == 1) then
    --存在，重复下单，返回2
    return 2
end

--3.5 扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
--3.6 下单（保存用户）sadd orderKey userId
redis.call('sadd', orderKey, userId)

--3.7 发送消息到队列中，XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0