---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangbiliu.
--- DateTime: 2025/4/27 17:24
---

--1.参数列表：
--1.1 优惠券id
local voucherId = ARGV[1]
--1.2 用户id
local userId = ARGV[2]
--1.3 当前时间(毫秒时间戳)
local currentTime = tonumber(ARGV[3])
--1.4 开始时间(毫秒时间戳)
local beginTime = tonumber(ARGV[4])
--1.5 结束时间(毫秒时间戳)
local endTime = tonumber(ARGV[5])

--2.数据key
--2.1 库存key
local stockKey = 'seckill:stock:' ..voucherId
--2.2 订单key
local orderKey = "seckill:order:" ..voucherId

--3.脚本业务
--3.1 判断秒杀时间是否开始
if (currentTime < beginTime) then
    --秒杀尚未开始，返回3
    return 3
end

--3.2 判断秒杀时间是否结束
if (currentTime > endTime) then
    --秒杀已经结束，返回4
    return 4
end

--3.3 判断库存是否充足
local stockStr = redis.call('get', stockKey)
if (stockStr == nil or tonumber(stockStr) <= 0) then
    --库存不足，返回1
    return 1
end

--3.4 判断用户是否下单  SISMEMBER orderKey userId
if (redis.call("sismember", orderKey, userId) == 1) then
    --存在，重复下单，返回2
    return 2
end

--3.5 扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
--3.6 下单（保存用户）sadd orderKey userId
redis.call('sadd', orderKey, userId)
--3.7 下单成功，返回0
return 0